"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";

type Project={id:number;title:string;type:string;year:string;image?:string|null};
type Media={id:number;project_id:number;type:string;url:string;alt:string;created_at:string};

export default function Dashboard(){
 const [projects,setProjects]=useState<Project[]>([]),[media,setMedia]=useState<Media[]>([]),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const p=await fetch("/api/projects",{cache:"no-store"}).then(r=>r.json());setProjects(p);const all=await Promise.all(p.map((x:Project)=>fetch(`/api/projects/${x.id}/media`,{cache:"no-store"}).then(r=>r.ok?r.json():[])));setMedia(all.flat());setLoading(false)})()},[]);
 const types=["all",...Array.from(new Set(projects.map(p=>p.type).filter(Boolean)))];
 const filtered=useMemo(()=>projects.filter(p=>(filter==="all"||p.type===filter)&&(`${p.title} ${p.type} ${p.year}`).toLowerCase().includes(query.toLowerCase())),[projects,filter,query]);
 return <div className="dashboardShell"><aside className="dashboardSidebar"><div className="brand">D<span>.</span></div><nav><Link className="active" href="/admin">Overview</Link><Link href="#projects">Projects</Link><Link href="#media">Media Library</Link><Link href="/">View Website ↗</Link></nav><div className="sidebarBottom"><span>ADMIN MODE</span><strong>Portfolio CMS</strong></div></aside><main className="dashboardMain"><header className="dashboardTop"><div><span className="sectionLabel">Control Center</span><h1>Good to see you.</h1></div><Link className="newButton" href="/admin#new">＋ New Project</Link></header><section className="statGrid"><article><span>PROJECTS</span><strong>{projects.length}</strong><small>Published works</small></article><article><span>MEDIA</span><strong>{media.length}</strong><small>Images & videos</small></article><article><span>VIDEOS</span><strong>{media.filter(m=>m.type==="video").length}</strong><small>Showcase clips</small></article><article><span>TYPES</span><strong>{types.length-1}</strong><small>Creative categories</small></article></section><section className="dashboardPanel" id="projects"><div className="panelHeader"><div><span className="sectionLabel">Library</span><h2>Projects</h2></div><div className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects..."/><select value={filter} onChange={e=>setFilter(e.target.value)}>{types.map(t=><option key={t} value={t}>{t==='all'?'All types':t}</option>)}</select></div></div>{loading?<div className="emptyPanel">Loading your workspace…</div>:filtered.length===0?<div className="emptyPanel">No projects match your search.</div>:<div className="projectTable">{filtered.map(p=><div className="projectRow" key={p.id}><div className="projectThumb">{p.image?<img src={p.image} alt=""/>:<span>{p.title.slice(0,1)}</span>}</div><div><strong>{p.title}</strong><small>{p.type} · {p.year}</small></div><span className="rowMedia">{media.filter(m=>m.project_id===p.id).length} media</span><Link href={`/admin#project-${p.id}`}>Edit →</Link></div>)}</div>}</section><section className="dashboardPanel" id="media"><div className="panelHeader"><div><span className="sectionLabel">Activity</span><h2>Recent uploads</h2></div><span className="liveDot">● LIVE</span></div><div className="recentGrid">{media.slice(-6).reverse().map(m=><div className="recentCard" key={m.id}>{m.type==="video"?<video src={m.url} muted/>:<img src={m.url} alt={m.alt}/>}<div><strong>{m.alt||"Untitled media"}</strong><span>{m.type.toUpperCase()}</span></div></div>)}</div></section></main></div>
}
