"use client";
import { useEffect, useState } from "react";
type Project={id:number;title:string;type:string;year:string};
type Media={id:number;project_id:number;type:"image"|"video";url:string;alt:string;sort_order:number};
export default function ProjectEditor(){
 const [projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState<number|null>(null),[media,setMedia]=useState<Media[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/projects",{cache:"no-store"});if(r.ok){const p=await r.json();setProjects(p);if(selected===null&&p[0])setSelected(p[0].id)}}
 async function loadMedia(id:number){const r=await fetch(`/api/projects/${id}/media`,{cache:"no-store"});setMedia(r.ok?await r.json():[])}
 useEffect(()=>{load()},[]);useEffect(()=>{if(selected)loadMedia(selected)},[selected]);
 async function upload(files:FileList|null){if(!files||!selected)return;setBusy(true);for(const file of Array.from(files)){const body=new FormData();body.append("file",file);const r=await fetch("/api/upload",{method:"POST",body});const data=await r.json();if(r.ok)await fetch(`/api/projects/${selected}/media`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:data.url,type:data.type,alt:file.name,sortOrder:media.length})});else setMessage(data.error||"Upload failed.")}await loadMedia(selected);setBusy(false);setMessage("Media uploaded ✓")}
 async function remove(id:number){await fetch(`/api/projects/${selected}/media/${id}`,{method:"DELETE"});if(selected)loadMedia(selected)}
 async function move(index:number,direction:number){const next=index+direction;if(next<0||next>=media.length||!selected)return;const copy=[...media];[copy[index],copy[next]]=[copy[next],copy[index]];setMedia(copy);await fetch(`/api/projects/${selected}/media/reorder`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids:copy.map(x=>x.id)})})}
 return <section className="editor"><div className="sectionLabel">Project Editor</div><h2>Edit your work.</h2><div className="editorSelect"><select value={selected??""} onChange={e=>setSelected(Number(e.target.value))}><option value="" disabled>Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></div>{selected&&<><label className="uploadButton">{busy?"Uploading…":"＋ Add images / videos"}<input multiple type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/quicktime" onChange={e=>upload(e.target.files)}/></label><div className="editorMedia">{media.map((item,index)=><article className="mediaItem" key={item.id}>{item.type==="video"?<video src={item.url} controls/>:<img src={item.url} alt={item.alt}/>}<div><span>{item.type.toUpperCase()}</span><button onClick={()=>move(index,-1)}>↑</button><button onClick={()=>move(index,1)}>↓</button><button onClick={()=>remove(item.id)}>Delete</button></div></article>)}</div></>}{message&&<p className="formStatus">{message}</p>}</section>
}
