"use client";
import { motion, useMotionValue, useSpring, useTransform } from "framer-motion";
import { useEffect, useState } from "react";

type Profile={name:string;role:string;bio:string;avatar:string;skills:string[];github:string;instagram:string;linkedin:string;email:string};
type Project={id:number;slug:string;title:string;type:string;year:string;description:string;image?:string|null};
const fallback:Profile={name:"Danial",role:"Creative Developer · Builder · Explorer",bio:"I build digital experiences, creative tools and products with a cinematic eye for detail.",avatar:"",skills:["Next.js / React","TypeScript / JavaScript","Python","UI / Motion / Creative"],github:"",instagram:"",linkedin:"",email:""};

function Cursor(){const x=useMotionValue(-100),y=useMotionValue(-100),sx=useSpring(x,{stiffness:450,damping:35}),sy=useSpring(y,{stiffness:450,damping:35});const [active,setActive]=useState(false);useEffect(()=>{const move=(e:MouseEvent)=>{x.set(e.clientX);y.set(e.clientY)};const over=(e:MouseEvent)=>{const el=e.target as HTMLElement;setActive(!!el.closest("a,button,[data-cursor]"))};window.addEventListener("mousemove",move);window.addEventListener("mouseover",over);return()=>{window.removeEventListener("mousemove",move);window.removeEventListener("mouseover",over)}},[x,y]);return <motion.div className="cursor" style={{x:sx,y:sy,width:active?48:20,height:active?48:20,margin:active?"-24px 0 0 -24px":"-10px 0 0 -10px"}}/>}

function Magnetic({children,href,secondary=false}:{children:React.ReactNode;href:string;secondary?:boolean}){const x=useMotionValue(0),y=useMotionValue(0);const sx=useSpring(x,{stiffness:300,damping:18}),sy=useSpring(y,{stiffness:300,damping:18});return <motion.a data-cursor className={`button ${secondary?"secondary":""}`} href={href} style={{x:sx,y:sy}} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();x.set((e.clientX-r.left-r.width/2)*.18);y.set((e.clientY-r.top-r.height/2)*.18)}} onMouseLeave={()=>{x.set(0);y.set(0)}} whileTap={{scale:.96}}>{children}</motion.a>}

function ProjectCard({project,index}:{project:Project;index:number}){const rx=useMotionValue(0),ry=useMotionValue(0),srx=useSpring(rx,{stiffness:220,damping:25}),sry=useSpring(ry,{stiffness:220,damping:25});return <motion.a data-cursor href={`/projects/${project.slug}`} className="card" style={{perspective:1000,rotateX:srx,rotateY:sry,overflow:"hidden",minHeight:360}} initial={{opacity:0,y:70}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-80px"}} transition={{duration:.7,delay:index*.08,ease:[.22,1,.36,1]}} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();rx.set(-((e.clientY-r.top)/r.height-.5)*5);ry.set(((e.clientX-r.left)/r.width-.5)*5)}} onMouseLeave={()=>{rx.set(0);ry.set(0)}}><div style={{position:"absolute",inset:0,background:project.image?`url(${project.image}) center/cover`:"radial-gradient(circle at 50% 20%,#292929,#0a0a0a 62%)",opacity:.7,transform:"scale(1.04)",transition:"transform .7s"}}/><div style={{position:"absolute",inset:0,background:"linear-gradient(180deg,rgba(0,0,0,.05),rgba(0,0,0,.9) 90%)"}}/><div style={{position:"relative",zIndex:2,height:"100%",minHeight:360,display:"flex",flexDirection:"column",justifyContent:"flex-end",padding:28}}><div className="sectionLabel">{String(index+1).padStart(2,"0")} · {project.type||"PROJECT"} · {project.year||"—"}</div><h3 style={{fontSize:"clamp(30px,4vw,52px)",margin:"10px 0",letterSpacing:"-.06em"}}>{project.title}</h3><p style={{maxWidth:520}}>{project.description}</p><span className="cardArrow">↗</span></div></motion.a>}

function ContactForm(){const[f,setF]=useState({name:"",email:"",subject:"",message:""}),[s,setS]=useState("");async function submit(e:React.FormEvent){e.preventDefault();setS("Sending…");const r=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(f)});setS(r.ok?"Message sent ✓":"Could not send message.");if(r.ok)setF({name:"",email:"",subject:"",message:""})}return <form className="contactForm" onSubmit={submit}><input required placeholder="Your name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input required type="email" placeholder="Email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input placeholder="Subject" value={f.subject} onChange={e=>setF({...f,subject:e.target.value})}/><textarea required placeholder="Tell me about your idea…" value={f.message} onChange={e=>setF({...f,message:e.target.value})}/><Magnetic href="#contact">Send message ↗</Magnetic>{s&&<span className="formStatus">{s}</span>}</form>}

export default function Home(){const[p,setP]=useState<Profile>(fallback),[projects,setProjects]=useState<Project[]>([]),[scroll,setScroll]=useState(0);useEffect(()=>{fetch("/api/profile",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(x=>x&&setP({...x,skills:Array.isArray(x.skills)?x.skills:JSON.parse(x.skills||"[]")})).catch(()=>{});fetch("/api/projects",{cache:"no-store"}).then(r=>r.ok?r.json():[]).then(setProjects).catch(()=>{});const on=()=>{const max=document.documentElement.scrollHeight-window.innerHeight;setScroll(max?window.scrollY/max:0)};window.addEventListener("scroll",on,{passive:true});return()=>window.removeEventListener("scroll",on)},[]);return <main className="site"><Cursor/><motion.div style={{position:"fixed",top:0,left:0,right:0,height:2,background:"#fff",transformOrigin:"0 50%",scaleX:scroll,zIndex:200}}/><div className="noise"/>
<nav className="nav"><motion.a data-cursor className="logo" href="#top" whileHover={{scale:1.08}}>D.</motion.a><div className="navLinks"><a href="#about">About</a><a href="#projects">Work</a><a href="#skills">Skills</a><a href="#contact">Contact</a></div><span className="status"><i/> Available for work</span></nav>
<section className="hero" id="top"><motion.div className="heroGlow" initial={{scale:.3,opacity:0}} animate={{scale:1,opacity:1}} transition={{duration:1.5,ease:[.22,1,.36,1]}}/><motion.div className="heroInner" initial={{opacity:0,y:80}} animate={{opacity:1,y:0}} transition={{duration:1,ease:[.22,1,.36,1]}}>{p.avatar&&<motion.img className="profileAvatar" src={p.avatar} alt={p.name} initial={{scale:0}} animate={{scale:1}} transition={{delay:.35,type:"spring"}}/>}<motion.span className="kicker" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:.25}}>{p.role||fallback.role}</motion.span><h1 className="title">I&apos;m <motion.span className="gradient" animate={{backgroundPosition:["0% 50%","100% 50%","0% 50%"]}} transition={{duration:7,repeat:Infinity}}>{p.name||fallback.name}.</motion.span></h1><motion.p className="subtitle" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.65}}>{p.bio||fallback.bio}</motion.p><div className="actions"><Magnetic href="#projects">Explore my work ↗</Magnetic><Magnetic href="#contact" secondary>Let&apos;s talk</Magnetic></div></motion.div><motion.div className="scrollHint" animate={{y:[0,8,0],opacity:[.45,1,.45]}} transition={{duration:2,repeat:Infinity}}>SCROLL ↓</motion.div></section>
<section className="section" id="about"><motion.div initial={{opacity:0,x:-30}} whileInView={{opacity:1,x:0}} viewport={{once:true}} className="sectionLabel">01 — About</motion.div><motion.h2 initial={{opacity:0,y:40}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.7}} className="sectionTitle">More than a portfolio.</motion.h2><div style={{display:"grid",gridTemplateColumns:"1.2fr .8fr",gap:40}}><motion.p className="subtitle" style={{margin:0,maxWidth:700}} initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true}}>{p.bio||fallback.bio}</motion.p><div className="sectionLabel" style={{alignSelf:"end"}}>BUILD · DESIGN · EXPERIMENT · SHIP</div></div></section>
<section className="section" id="projects"><div className="sectionLabel">02 — Selected Work</div><motion.h2 className="sectionTitle" initial={{opacity:0,y:40}} whileInView={{opacity:1,y:0}} viewport={{once:true}}>Things I&apos;ve built.</motion.h2><div className="grid">{projects.slice(0,6).map((x,i)=><ProjectCard key={x.id} project={x} index={i}/>)}{!projects.length&&["Dyolmeh","CineVault"].map((x,i)=><motion.article className="card" key={x} initial={{opacity:0,y:50}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><div className="sectionLabel">0{i+1}</div><h3>{x}</h3><p>Project content will appear here once you add it from the Admin CMS.</p></motion.article>)}</div><div style={{marginTop:28}}><Magnetic href="/projects" secondary>View all projects →</Magnetic></div></section>
<section className="section" id="skills"><div className="sectionLabel">03 — Skills</div><motion.h2 className="sectionTitle" initial={{opacity:0,y:40}} whileInView={{opacity:1,y:0}} viewport={{once:true}}>Tools I work with.</motion.h2><div className="grid">{(p.skills.length?p.skills:fallback.skills).map((skill,i)=><motion.div className="card skillCard" key={skill} initial={{opacity:0,x:i%2?30:-30}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*.08}} whileHover={{y:-8}}><h3>{skill}</h3><span>{String(i+1).padStart(2,"0")}</span></motion.div>)}</div></section>
<section className="section contact" id="contact"><div className="sectionLabel">04 — Contact</div><motion.h2 className="sectionTitle" initial={{opacity:0,y:50}} whileInView={{opacity:1,y:0}} viewport={{once:true}}>Let&apos;s make something.</motion.h2><div className="contactGrid"><div><p className="subtitle" style={{margin:0}}>Have an idea, project or collaboration in mind? Let&apos;s build something worth remembering.</p><div className="socials">{p.email&&<a data-cursor href={`mailto:${p.email}`}>Email ↗</a>}{p.github&&<a data-cursor href={p.github} target="_blank">GitHub ↗</a>}{p.instagram&&<a data-cursor href={p.instagram} target="_blank">Instagram ↗</a>}{p.linkedin&&<a data-cursor href={p.linkedin} target="_blank">LinkedIn ↗</a>}</div></div><ContactForm/></div></section><footer className="footer">© 2026 {p.name||fallback.name}. Built with curiosity.</footer></main>}
