"use client";
import { motion, useMotionValue, useSpring } from "framer-motion";
import { useEffect, useState } from "react";

type Profile={name:string;role:string;bio:string;avatar:string;skills:string[];github:string;instagram:string;linkedin:string;email:string};
type Project={id:number;slug:string;title:string;type:string;year:string;description:string;image?:string|null};
type SectionConfig={enabled:boolean;order:number;[key:string]:any};
const fallback:Profile={name:"Danial",role:"Creative Developer",bio:"I build digital experiences, creative tools and products with a cinematic eye for detail.",avatar:"",skills:["Next.js / React","TypeScript / JavaScript","Python","UI / Motion / Creative"],github:"",instagram:"",linkedin:"",email:""};
const defaults:any={hero:{enabled:true,order:1,kicker:"Creative Developer",titlePrefix:"I'm",title:"Danial.",subtitle:fallback.bio},about:{enabled:true,order:2,title:"More than a portfolio."},skills:{enabled:true,order:3,title:"Tools I work with."},experience:{enabled:true,order:4,title:"Experience."},projects:{enabled:true,order:5,title:"Things I've built.",limit:6},contact:{enabled:true,order:6,title:"Let's make something."},footer:{enabled:true,order:7,text:"Built with curiosity."}};
function Cursor(){const x=useMotionValue(-100),y=useMotionValue(-100),sx=useSpring(x,{stiffness:450,damping:35}),sy=useSpring(y,{stiffness:450,damping:35}),[active,setActive]=useState(false);useEffect(()=>{const m=(e:MouseEvent)=>{x.set(e.clientX);y.set(e.clientY);setActive(!!(e.target as HTMLElement).closest("a,button"))};addEventListener("mousemove",m);return()=>removeEventListener("mousemove",m)},[x,y]);return <motion.div className="cursor" style={{x:sx,y:sy,width:active?48:20,height:active?48:20,margin:active?"-24px 0 0 -24px":"-10px 0 0 -10px"}}/>}
function Magnetic({children,href,secondary=false}:{children:React.ReactNode;href:string;secondary?:boolean}){const x=useMotionValue(0),y=useMotionValue(0),sx=useSpring(x,{stiffness:300,damping:18}),sy=useSpring(y,{stiffness:300,damping:18});return <motion.a className={`button ${secondary?"secondary":""}`} href={href} style={{x:sx,y:sy}} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();x.set((e.clientX-r.left-r.width/2)*.18);y.set((e.clientY-r.top-r.height/2)*.18)}} onMouseLeave={()=>{x.set(0);y.set(0)}} whileTap={{scale:.96}}>{children}</motion.a>}
function ProjectCard({project,index}:{project:Project;index:number}){return <motion.a href={`/projects/${project.slug}`} className="card projectCard" initial={{opacity:0,y:70}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-80px"}} transition={{duration:.7,delay:index*.08}} whileHover={{y:-10}}><div className="projectImage" style={project.image?{backgroundImage:`url(${project.image})`}:{}}><span>VIEW ↗</span></div><div className="projectMeta"><div><div className="sectionLabel">{String(index+1).padStart(2,"0")} · {project.type||"PROJECT"} · {project.year||"—"}</div><h3>{project.title}</h3><p>{project.description}</p></div></div></motion.a>}
export default function Home(){const[p,setP]=useState<Profile>(fallback),[config,setConfig]=useState<any>(defaults),[projects,setProjects]=useState<Project[]>([]);useEffect(()=>{Promise.all([fetch("/api/profile",{cache:"no-store"}).then(r=>r.ok?r.json():null),fetch("/api/home",{cache:"no-store"}).then(r=>r.ok?r.json():null),fetch("/api/projects",{cache:"no-store"}).then(r=>r.ok?r.json():[])]).then(([profile,home,items])=>{if(profile)setP({...profile,skills:Array.isArray(profile.skills)?profile.skills:JSON.parse(profile.skills||"[]")});if(home)setConfig(home);setProjects(Array.isArray(items)?items:(items?.projects||[]))}).catch(()=>{})},[]);const c={...defaults,...config};const sections=Object.entries(c).filter(([,v]:any)=>v.enabled).sort((a:any,b:any)=>a[1].order-b[1].order);const render=(key:string,v:SectionConfig)=>{if(key==="hero")return <section className="hero" id="top" key={key}><div className="heroGlow"/><div className="heroInner"><span className="kicker">{v.kicker||p.role}</span><h1 className="title">{v.titlePrefix||"I'm"} <span className="gradient">{v.title||p.name+"."}</span></h1><p className="subtitle">{v.subtitle||p.bio}</p><div className="actions"><Magnetic href="#projects">Explore my work ↗</Magnetic><Magnetic href="#contact" secondary>Let's talk</Magnetic></div></div><div className="scrollHint">SCROLL ↓</div></section>;
if(key==="about")return <section className="section" id="about" key={key}><div className="sectionLabel">01 — About</div><motion.h2 className="sectionTitle" initial={{opacity:0,y:40}} whileInView={{opacity:1,y:0}} viewport={{once:true}}>{v.title}</motion.h2><p className="subtitle">{p.bio}</p></section>;
if(key==="skills")return <section className="section" id="skills" key={key}><div className="sectionLabel">02 — Skills</div><h2 className="sectionTitle">{v.title}</h2><div className="grid">{(p.skills.length?p.skills:fallback.skills).map((s,i)=><motion.div className="card skillCard" key={s} initial={{opacity:0,x:i%2?30:-30}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*.08}} whileHover={{y:-8}}><h3>{s}</h3><span>{String(i+1).padStart(2,"0")}</span></motion.div>)}</div></section>;
if(key==="experience")return <section className="section" id="experience" key={key}><div className="sectionLabel">03 — Experience</div><h2 className="sectionTitle">{v.title}</h2><div className="experience"><div><span>01</span><h3>Creative Development</h3><p>Digital products, websites and creative tools.</p></div><div><span>02</span><h3>Design & Motion</h3><p>Visual systems, interaction and cinematic motion.</p></div><div><span>03</span><h3>Independent Projects</h3><p>From concept to launch.</p></div></div></section>;
if(key==="projects")return <section className="section" id="projects" key={key}><div className="sectionLabel">04 — Selected Work</div><h2 className="sectionTitle">{v.title}</h2><div className="grid">{projects.slice(0,v.limit||6).map((x,i)=><ProjectCard key={x.id} project={x} index={i}/>)}</div></section>;
if(key==="contact")return <section className="section contact" id="contact" key={key}><div className="sectionLabel">05 — Contact</div><h2 className="sectionTitle">{v.title}</h2><p className="subtitle">Have an idea, project or collaboration in mind? Let's build something worth remembering.</p><div className="socials">{p.email&&<a href={`mailto:${p.email}`}>Email ↗</a>}{p.github&&<a href={p.github} target="_blank">GitHub ↗</a>}{p.instagram&&<a href={p.instagram} target="_blank">Instagram ↗</a>}{p.linkedin&&<a href={p.linkedin} target="_blank">LinkedIn ↗</a>}</div></section>;
if(key==="footer")return <footer className="footer" key={key}>© 2026 {p.name}. {v.text}</footer>;return null};return <main className="site"><Cursor/><div className="noise"/><nav className="nav"><a className="logo" href="#top">{(p.name||"D").charAt(0)}.</a><div className="navLinks"><a href="#about">About</a><a href="#projects">Work</a><a href="#skills">Skills</a><a href="#contact">Contact</a></div><span className="status"><i/> Available</span></nav>{sections.map(([key,v]:any)=>render(key,v))}</main>}
